---
global_config:
  environment_name: cloudpak
  cloud_platform: existing-ocp
  env_id: ocp
  confirm_destroy: True

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.16
  cluster_name: PATCHED_BY_JOB
  domain_name: PATCHED_BY_JOB
  gpu:
    install: False
  openshift_ai:
    install: False
    channel: fast
  mcg:
    install: False
    storage_type: storage-class
    storage_class: ibm-storage-fusion-cp-sc
  openshift_storage:
  - storage_name: custom
    storage_type: custom
    ocp_storage_class_file: ocs-storagecluster-cephfs
    ocp_storage_class_block: ocs-storagecluster-ceph-rbd
